site_name: Notes
site_url: https://hari31416.github.io/Notes/
repo_url: https://github.com/Hari31416/Notes
repo_name: Notes
site_author: Harikesh Kushwaha
remote_branch: gh-pages
site_description: "A collection of my notes as well as some external materials"
remote_name: origin

theme:
  name: material
  logo: assets/ml.png
  favicon: assets/ml.png
  features:
    - navigation.instant
    - navigation.top
    - toc.integrate
  palette:
    primary: black
  custom_dir: all_notebooks

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - mknotebooks
  - search
  - mike

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

edit_uri: ""

nav:
  - Home: "index.md"
  - Notes:
      - DL:
          - Notes/DL/CNN.ipynb
          - Notes/DL/Creating_NN_From_Scratch.ipynb
          - Notes/DL/Different_Initializations.ipynb
          - Notes/DL/Neural_Networks.ipynb
          - Notes/DL/Optimization_Methods.ipynb
          - Notes/DL/Sequence_Models.ipynb
          - Notes/DL/temp.ipynb
      - DSA:
          - Notes/DSA/Bitwise_operators.ipynb
          - Notes/DSA/Doubly_Linked_List.ipynb
          - Notes/DSA/LinkedList.ipynb
          - Notes/DSA/Problems_GfG_Easy_1.ipynb
          - Notes/DSA/Problems_GfG_Easy_2.ipynb
          - Notes/DSA/Problems_GfG_Easy_3.ipynb
          - Notes/DSA/Problems_GfG_Easy_4.ipynb
          - Notes/DSA/Problems_Leetcode_Easy_1.ipynb
          - Notes/DSA/Problems_Leetcode_Easy_2.ipynb
          - Notes/DSA/Problems_Leetcode_Easy_3.ipynb
          - Notes/DSA/Problems_Leetcode_Easy_4.ipynb
          - Notes/DSA/Problems_Leetcode_Easy_5.ipynb
          - Notes/DSA/Problems_Leetcode_Easy_6.ipynb
          - Notes/DSA/Problems_Leetcode_Hard_1.ipynb
          - Notes/DSA/Problems_Leetcode_Medium_1.ipynb
          - Notes/DSA/Problems_Leetcode_Medium_2.ipynb
          - Notes/DSA/Problems_Leetcode_Medium_3.ipynb
          - Notes/DSA/Recursion.ipynb
          - Notes/DSA/Stack_and_Queue.ipynb
          - Notes/DSA/Trees.ipynb
      - Finance:
          - Notes/Finance/Black_Scholes_Model.ipynb
          - Notes/Finance/CAPM.ipynb
          - Notes/Finance/Five_Factor_Model.ipynb
          - Notes/Finance/Forward_Future.ipynb
          - Notes/Finance/Market_Hypothesis.ipynb
          - Notes/Finance/Module_1.ipynb
          - Notes/Finance/Module_2.ipynb
          - Notes/Finance/Module_3.ipynb
          - Notes/Finance/Module_4.ipynb
          - Notes/Finance/Module_5.ipynb
          - Notes/Finance/Module_6.ipynb
          - Notes/Finance/Module_7.ipynb
          - Notes/Finance/Working_With_pystock.ipynb
      - ML:
          - Notes/ML/Clustering.ipynb
          - Notes/ML/Decision_Trees.ipynb
          - Notes/ML/Ensemble_Learning.ipynb
          - Notes/ML/Feature_Selection.ipynb
          - Notes/ML/Linear_Regression.ipynb
          - Notes/ML/Logistic_Regression.ipynb
          - Notes/ML/Multiclass_Multioutput_Algorithm.ipynb
          - Notes/ML/Nearest_Neighbors.ipynb
          - Notes/ML/Stochastic_Gradient_Descent.ipynb
          - Notes/ML/Support_Vector_Machine.ipynb
      - Python:
          - Notes/Python/OOP.ipynb
          - Notes/Python/Programming_Language_Terms.ipynb
          - Notes/Python/Programming_Paradigms.ipynb
          - Notes/Python/Scope_and_Namespace.ipynb
          - Notes/Python/Terminology.ipynb
          - Notes/Python/Variables_and_Pointers.ipynb
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hari31416
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hari31416
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hari31416
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/hari31416
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/hari31416
  version:
    provider: mike
